export const FETCH_NOTE = 'FETCH_NOTE';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAIL = 'FETCH_NOTE_FAIL';

export const REPLAY_SONG = 'REPLAY_SONG';
export const REPLAY_SONG_SUCCESS = 'REPLAY_SONG_SUCCESS';
export const REPLAY_SONG_FAIL = 'REPLAY_SONG_FAIL';

export const PLAY_SONG = 'PLAY_SONG';
export const PLAY_SONG_SUCCESS = 'PLAY_SONG_SUCCESS';
export const PLAY_SONG_FAIL = 'PLAY_SONG_FAIL';

export const CHECK_ANSWER = 'CHECK_ANSWER';
export const CHECK_ANSWER_SUCCESS = 'CHECK_ANSWER_SUCCESS';
export const CHECK_ANSWER_FAIL = 'CHECK_ANSWER_FAIL';

export const GET_REPORT = 'GET_REPORT';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';
